spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

#  datasource:
#    initialize: true
#    url: jdbc:h2:mem:testdb
#    username: sa

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 9658229605...
            client-secret: GOCSPX-bk42...
            scope:
              - email
              - profile

jwt:
  issuer: ajufresh@gmail.com
  secret_key: b355070...

aws:
  s3:
    bucket-name: devkord-img
    access-key: AKIA5...
    secret-key: X5bPT...
    region: ap-northeast-2